pepero-1/liar-game

- src/hooks/useFetch.ts
- src/hooks/useFireFetch.ts
- src/index.css
- src/pages/Example/index.tsx
- src/pages/Login/index.tsx
- useFetch 리턴값 수정
변경
```javascript
return { result, loading, statusCode, refresh };
```
사용
```javascript
const users = useFetch({
url: "https://fastcampus-chat.net/users",
method: "GET",
start: true,
});
console.log(users.result, users.loading, users.statusCode)
```
```javascript
const login = useFetch({
url: "https://fastcampus-chat.net/login",
method: "POST",
data: data,
start: false,
});
const handleLogin = () => {
login.refresh();
};
```
- 커스텀 훅 변경으로 login페이지와, example페이지가 수정되었습니다.
- index.css 수정
```css
#root {
max-width: 1200px;
margin: 0 auto;
}
```
> useFireFetch, useFetch, index.css 수정

- src/hooks/useFetch.ts
- src/hooks/useFireFetch.ts
- src/pages/Example/index.tsx
- 커스텀 훅 타입 및 환경변수를 추가했습니다.
- 예시 페이지에 소켓통신에 대한 코드를 작성했습니다.
> 커스텀 훅 타입 및 환경변수 추가, 예시 페이지 소켓통신 추가

- src/components/Main/CreateGameModal/index.tsx
- src/components/common/UserCard/index.tsx
- src/pages/Example/index.tsx
- src/pages/Login/index.tsx
> 유저초대, 초대 알림 기능

- src/App.tsx
- src/components/Main/CreateGameModal/index.tsx
- src/hooks/useFireFetch.ts
게임 생성 시 게임 페이지로 이동됩니다.
ex) /game?gameId="asdasdasdasdasdasdasd"
> 게임 생성 시 게임 페이지로 이동

- src/components/Main/CreateGameModal/index.tsx
- src/components/common/UserCard/index.tsx
- src/pages/Game/index.tsx
- 데이터 예시
```javascript
// http://localhost:5173/game?gameId=302d3afc-fd97-41a9-82e0-b7ad923ba1d2 여기로 이동해보시면 됩니다
[
{
"status": "대기중",
"name": "testtttt",
"isPrivate": false,
"createdAt": {
"seconds": 1699510561,
"nanoseconds": 599000000
},
"host": "sue123",
"bg": "⭐",
"id": "302d3afc-fd97-41a9-82e0-b7ad923ba1d2",
"num": 1,
"users": [
"qwer1234"
]
}
]
```
> 게임 입장 시 콘솔에 데이터 출력

- src/components/Main/CreateGameModal/index.tsx
- src/components/common/ToastNotice/index.tsx
- src/pages/Example/index.tsx
- 초대 수락 시 해당 게임id에 대한 페이지로 이동합니다.
- 초대 거절 시 해당 게임 방에서 자동으로 나와집니다.
- 토스트 팝업 ui가 초대한 게임의 정보, 호스트 정보와 연동이 되어 화면에 보여집니다.
> 토스트 팝업 ui 데이터 연결, 초대 거절 수락 기능 추가

- src/components/Main/CreateGameModal/index.tsx
> 유저 초대 목록 표시 오류 수정

- src/components/Main/CreateGameModal/index.tsx
- src/components/common/ToastNotice/index.tsx
- src/components/common/UserCard/index.tsx
- src/hooks/useFetch.ts
- src/hooks/useSocket.ts
- src/pages/Example/index.tsx
useSocket() 사용 예시
- 기존
```javascript
const socket = io(`chatId`, {
extraHeaders: {
Authorization: `Bearer ${token.accessToken}`,
serverId: import.meta.env.VITE_APP_SERVER_ID,
},
});
useEffect(() => {
socket.on("message-to-client", (messageObject) => {
// 소켓 통신 데이터 (통신 시 작동 시키고 싶은 함수 작성)
console.log(messageObject);
});
}, [socket]);
// 메시지 보내기
const submitMessage = () => {
socket.emit(text);
};
```
- 변경
```javascript
const sendMessage = useSocket("chatId", (messageObject) => {
// 소켓 통신 데이터 (통신 시 작동 시키고 싶은 함수 작성)
console.log(messageObject)
});
// 메시지 보내기
const submitMessage = () => {
sendMessage(text);
};
```
> 소켓 통신 useSocket 추가, 토스트 알람 UI 일부 수정

- src/components/Main/GameLists/index.tsx
*  유저정보 불러오기 + UI 적용
* 전체유저정보 불러오기 + UI 적용
> Feature/#7 게임 목록 페이지 유저정보 , 전체유저정보 구현

- src/components/Main/CreateGameModal/index.tsx
- src/components/common/ToastNotice/index.tsx
- src/components/common/UserCard/index.tsx
- src/hooks/useFetch.ts
- src/pages/Example/index.tsx
- 게임 생성 시 유저 초대할 때 인원수 제한 넘기면 경고
- 게임 초대 메시지 수락 버튼 눌러야 게임 입장 가능으로 수정
> [FIX] 초대 인원 제한, 게임 초대 수락 시 게임 입장

- src/components/Game/GameChat/index.tsx
- src/components/Login/LoginForm/index.tsx
- src/hooks/useAuth.ts
- src/pages/Login/index.tsx
- src/pages/Main/user/index.tsx
- src/recoil/atoms/userState.ts
- 로그인시 아이디 로컬스토리지에 저장
- 리코일로 아이디 관리
<br>
사용자 아이디 로컬스토리지에서 불러오시거나, 혹시 리코일로 쓰실거면 Main/user 페이지 참고하시면 될 듯 합니다~!
> Feature/#9 로그인시 아이디 저장

- src/components/Main/CreateGameModal/index.tsx
- src/hooks/useFetch.ts
- src/pages/Example/index.tsx
- 초대 팝업 가끔 안되는 오류 수정
- 로컬스토리지의 토큰, 유저 정보 가져오는 부분을 리코일 함수를 통해 가져오도록 수정하였습니다.
> 초대 팝업 오류 수정, 유저 정보 리코일로 가져오기

- src/components/Main/CreateGameModal/index.tsx
- src/components/common/ToastNotice/index.tsx
- src/pages/Example/index.tsx
> 게임 입장 시 파이어베이스 업데이트

- src/components/Main/GameCard/index.tsx
- src/components/Main/GameLists/index.tsx
* 게임방 리스트 불러오기
* 게임방 데이터 적용하기 
* 게임 진행상황 적용
* 전체채팅
> Feature/#7 게임방 리스트 불러오기 , 게임방 데이터 적용하기

- src/components/Game/GameChat/index.tsx
- src/components/Game/GameStart/index.tsx
- src/components/Main/CreateGameModal/index.tsx
- src/pages/Example/index.tsx
- src/pages/Game/index.tsx
* 게임 시작 버튼 클릭 시 유저 발언 순서, 카테고리, 키워드 로컬스토리에 저장
* 실시간 렌더링을 위한 비동기 처리
> Feat/#3: 게임 시작 소켓 연결

- package-lock.json
- package.json
- src/components/Main/CreateGameModal/index.tsx
- src/hooks/useFireFetch.ts
> esbuild 에러

- src/components/Main/GameLists/index.tsx
- src/pages/Main/user/index.tsx
- 로그아웃, 프로필 수정 GameLists로 연결
<br>
- 로그인해야만 GameLists 내용 보임.
> Feature/#32 로그아웃, 프로필 수정 GameLists로 연결

- src/components/Main/GameLists/index.tsx
- 로그아웃, 프로필 수정 GameLists로 연결
<br>
- 로그인해야만 GameLists 내용 보임.
> Feat: 로그아웃, 프로필 수정 GameLists로 연결 

- src/components/Game/GameChat/index.tsx
- src/components/Game/GameStart/index.tsx
- src/components/Game/Keyword/index.tsx
- src/components/Main/CreateGameModal/index.tsx
- src/pages/Game/index.tsx
* 게임 시작 시 로컬스토리지에 저장하던 데이터를 state 변수로 수정
* 게임 시작 버튼 클릭 시 카테고리, 키워드, 라이어, 유저 순서 배열 실시간 렌더링
* 게임 종료 버튼 클릭 시 위 정보들 초기화 (유저 순서는 유지)
* current, speaking 변수 추가 
* host 게임방 퇴장 시 게임시작버튼 권한 넘기기
* main 페이지로 게임방 상태 전달
> Feature/#3 게임 시작 구현

- src/components/Game/GameChat/index.tsx
- src/components/Game/Vote/index.tsx
- src/components/common/ChatBubble.tsx
- src/components/common/MyChatBubble.tsx
> 채팅 중복전송 오류 해결 

- src/components/Game/GameChat/index.tsx
- src/components/Game/Keyword/index.tsx
- src/components/Game/Timer/index.tsx
- src/components/common/ToastNotice/index.tsx
- src/pages/Example/index.tsx
- src/pages/Game/index.tsx
> game 로직 임시

- src/components/Main/GameLists/index.tsx
- src/components/Main/GameListsChat/index.tsx
* 게임방 리스트 페이지에 게임방 만들기 기능 연결
* 게임방 리스트 페이지에 있는 채팅 ui 분리
* 전체채팅 socket연결 및 확인 필요
> Feature/#7 게임방 리스트 페이지 에 게임방 만들기 기능 연결 , 게임방리스트 채팅 분리

- src/components/Login/LoginForm/index.tsx
- src/components/Login/SignUpModal/index.tsx
- src/hooks/useAuth.ts
- src/pages/Login/index.tsx
- console.log 제거
- import 순서 정리
> Feature/#32 console.log 제거

- src/components/Game/GameStart/GameStartModal.tsx
- src/components/Game/GameStart/index.tsx
- src/pages/Game/index.tsx
> Feat/#51: 게임 종료 시 current 상태 수정

- src/App.tsx
- src/components/Main/GameLists/index.tsx
- src/pages/Game/index.tsx
- src/pages/NotFound/index.tsx
- 로그인 안된 유저들의 다른 페이지로 접근을 막았습니다.
- 존재하지 않는 페이지 이동시 404 화면이 보여집니다.
> 유저 인증, 404 페이지 추가

- README.md
> Feature/#51 리드미 업데이트
